# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09fed2aceca3998ecb260f2e82b763209c5b37eaba59fa5ccf2130f7f6460f975a9da0de07d1dcf782cfc7547bb5d4ba4f8a4df7ab74bc2b3b197cf1ee5a533e

test:
  secret_key_base: 75944ee03ac5855b6d68d29f529a61e69d356ac3e608224d41113d53d78677fac2e90154485a28ea26337201fa21cb95b6a05a639f0476adf6325f6dcd389370

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
